### ISSUE TITLE
win10执行ncgen ./ncgen-config.js时报错

### ISSUE THREAD

**Issue by JackFruitxx** [daniel-dx/ncgen#5]
![image](https://user-images.githubusercontent.com/43942771/124910042-b88f3b00-e01d-11eb-985a-8103dadb0e2a.png)

**Comment by JackFruitxx** [comment]
![image](https://user-images.githubusercontent.com/43942771/124911863-d493dc00-e01f-11eb-922e-1984454805a4.png)

'rm' is not recognized as an internal or external command,

**Comment by daniel-dx** [comment]
refer to https://github.com/daniel-dx/ncgen/compare/develop?expand=1#diff-bae5a5f9a6d7194c667c7865eab65b35d72ce8b81f7d11851efa568a90d1c068
